In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

# Basic Pandas Syntax

In [5]:
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["Berlin", "Paris", "London"]
})

df.head()

      name  age    city
0    Alice   25  Berlin
1      Bob   30   Paris
2  Charlie   35  London

In [10]:
df = pd.DataFrame({
    'x' : range(6,0, -1),
    'y' : [True]*3 + [False]*3}
)

df.head()

   x      y
0  6   True
1  5   True
2  4   True
3  3  False
4  2  False

-------------

## Loading DataFrame

read_csv() & read_excel()

In [15]:
fligts = pd.read_csv('Datasets/LAX Uçuşları.csv',
                     usecols= ['YEAR', 'MONTH',
                                'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
                                'AIR_TIME', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
                                'DEPARTURE_TIME','DISTANCE', 'ARRIVAL_TIME']
                    )

fligts.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
0,2015,1,1,4,AA,2336,LAX,PBI,2.0,263.0,2330,741.0
1,2015,1,1,4,AA,258,LAX,MIA,15.0,258.0,2342,756.0
2,2015,1,1,4,US,2013,LAX,CLT,44.0,228.0,2125,753.0
3,2015,1,1,4,DL,1434,LAX,MSP,35.0,188.0,1535,605.0
4,2015,1,1,4,AA,115,LAX,MIA,103.0,255.0,2342,839.0

### shape

Note, that index is not counted as column

In [18]:
fligts.shape

(389369, 12)

### columns

In [19]:
fligts.columns

Index(['YEAR', 'MONTH', 'DAY', 'DAY_OF_WEEK', 'AIRLINE', 'FLIGHT_NUMBER',
       'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'DEPARTURE_TIME', 'AIR_TIME',
       'DISTANCE', 'ARRIVAL_TIME'],
      dtype='object')

### describe

In [20]:
fligts.iloc[:, :6].describe()

           YEAR          MONTH            DAY    DAY_OF_WEEK  FLIGHT_NUMBER
count  389369.0  389369.000000  389369.000000  389369.000000  389369.000000
mean     2015.0       6.197502      15.703389       3.934160    1905.390165
std         0.0       3.366953       8.779643       1.996267    1766.645447
min      2015.0       1.000000       1.000000       1.000000       1.000000
25%      2015.0       3.000000       8.000000       2.000000     501.000000
50%      2015.0       6.000000      16.000000       4.000000    1296.000000
75%      2015.0       9.000000      23.000000       6.000000    2617.000000
max      2015.0      12.000000      31.000000       7.000000    6896.000000

### unique

First we list all unique elements using in a categorical variable

In [22]:
fligts['AIRLINE'].unique()

array(['AA', 'US', 'DL', 'UA', 'OO', 'AS', 'B6', 'NK', 'VX', 'WN', 'HA',
       'F9', 'MQ'], dtype=object)

### value_counts

Another valuable information for categorical variables is how often each category
occurs:

In [26]:
fligts['AIRLINE'].value_counts()

AIRLINE
WN    75022
OO    73389
AA    65483
UA    54862
DL    50343
VX    23598
AS    16144
NK     8688
B6     8216
US     7374
HA     3112
F9     2770
MQ      368
Name: count, dtype: int64

---------

## Indices

* Every DataFrame has a row index
* Row index: labels each row (default = 0, 1, 2, ...)

In [28]:
fligts.index

RangeIndex(start=0, stop=389369, step=1)

Key points about row index:

* Can be costumized - any type: integers, strings, dates, tuples
* Does not have to be unique or ordered

------

### Subsetting a single row

.iloc[] (by position) or loc[] (by index, the same in our case)

In [30]:
fligts.iloc[1] # Access the 2nd row

YEAR                    2015
MONTH                      1
DAY                        1
DAY_OF_WEEK                4
AIRLINE                   AA
FLIGHT_NUMBER            258
ORIGIN_AIRPORT           LAX
DESTINATION_AIRPORT      MIA
DEPARTURE_TIME          15.0
AIR_TIME               258.0
DISTANCE                2342
ARRIVAL_TIME           756.0
Name: 1, dtype: object

------

### Subsetting multiple rows by position

In [32]:
fligts.iloc[0:2]

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
0,2015,1,1,4,AA,2336,LAX,PBI,2.0,263.0,2330,741.0
1,2015,1,1,4,AA,258,LAX,MIA,15.0,258.0,2342,756.0

In [33]:
fligts.iloc[[0,102]]

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
0,2015,1,1,4,AA,2336,LAX,PBI,2.0,263.0,2330,741.0
102,2015,1,1,4,AS,482,SEA,LAX,802.0,126.0,954,1025.0

---------

### Subsetting rows by logical conditions

Often, a more useful way to subset rows is using logical conditions, using a logical
vector instead of a vector of indices

* We can create such logical vectors using the following binary operators:
    - == 
    - <
    - \>
    - != 
    - isin()

In [36]:
fligts[ fligts['DESTINATION_AIRPORT'] == 'MIA'].head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
1,2015,1,1,4,AA,258,LAX,MIA,15.0,258.0,2342,756.0
4,2015,1,1,4,AA,115,LAX,MIA,103.0,255.0,2342,839.0
111,2015,1,1,4,AA,306,LAX,MIA,759.0,257.0,2342,1539.0
164,2015,1,1,4,AA,208,LAX,MIA,842.0,264.0,2342,1627.0
452,2015,1,1,4,AA,124,LAX,MIA,1305.0,256.0,2342,2042.0

In [38]:
fligts[ fligts['ORIGIN_AIRPORT'].isin(['JFK', 'EWR']) ].head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
40,2015,1,1,4,B6,23,JFK,LAX,627.0,358.0,2475,951.0
56,2015,1,1,4,UA,312,EWR,LAX,656.0,340.0,2454,1020.0
57,2015,1,1,4,VX,399,JFK,LAX,655.0,360.0,2475,1027.0
58,2015,1,1,4,AA,9,JFK,LAX,649.0,368.0,2475,1026.0
67,2015,1,1,4,DL,424,JFK,LAX,702.0,356.0,2475,1030.0

### | &, or and

In [40]:
fligts[ fligts['ORIGIN_AIRPORT'].isin(['JFK', 'EWR']) | 
        fligts['DESTINATION_AIRPORT'].isin(['JFK', 'EWR'])].head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
25,2015,1,1,4,UA,996,LAX,EWR,603.0,263.0,2454,1350.0
30,2015,1,1,4,B6,24,LAX,JFK,620.0,279.0,2475,1413.0
40,2015,1,1,4,B6,23,JFK,LAX,627.0,358.0,2475,951.0
53,2015,1,1,4,DL,476,LAX,JFK,650.0,274.0,2475,1458.0
56,2015,1,1,4,UA,312,EWR,LAX,656.0,340.0,2454,1020.0

In [51]:
fligts[ (fligts['DAY'] == 24) & (fligts['MONTH'] == 12) & (fligts['DESTINATION_AIRPORT'] == 'LAX')].tail(5)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
381556,2015,12,24,4,UA,1110,OGG,LAX,2241.0,285.0,2486.0,541.0
381557,2015,12,24,4,AA,14,OGG,LAX,2235.0,289.0,2486.0,546.0
381567,2015,12,24,4,AA,246,KOA,LAX,11.0,295.0,2504.0,741.0
381569,2015,12,24,4,UA,1229,HNL,LAX,2342.0,297.0,2556.0,706.0
381572,2015,12,24,4,AS,150,ANC,LAX,2355.0,254.0,2345.0,529.0

-------

## Missig Values

Missing values in pandas are encoded using np.nan for floats, NaT for datetime columns and pd.NA for all other data types.

In [43]:
fligts.loc[2, 'DISTANCE'] = np.nan

In [46]:
fligts[ fligts['DISTANCE'].isna() ]

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
2,2015,1,1,4,US,2013,LAX,CLT,44.0,228.0,NaN,753.0

------

## Column Operations

### Series

Each column of a DataFrame is a Series

In [55]:
destination = fligts['DESTINATION_AIRPORT']
type(destination)

pandas.core.series.Series

* A Series is one-dimensional labeled array
* It has two components:
    - Values (['PBI', 'MIA', 'CLT', ..., 'BOS'])
    - Index  ([0, 1, 2, ..., 389368])
* Supports operations like .mean() , .sum(), etc.

Since a DataFrame is just a collection of Series side by side, selecting a single column returns a corresponding Series.

----------

### Accessing one DataFrame entry

In [59]:
fligts.loc[5, 'DESTINATION_AIRPORT']

'IAH'

---------

### Accessing multiple columns

Note, that the returned object is a DataFrame

In [62]:
airport_columns = ['ORIGIN_AIRPORT', 'DESTINATION_AIRPORT']

fligts[airport_columns].head()

  ORIGIN_AIRPORT DESTINATION_AIRPORT
0            LAX                 PBI
1            LAX                 MIA
2            LAX                 CLT
3            LAX                 MSP
4            LAX                 MIA

-----

# Groupby Operation

Often we want to compute summaries per category, for example: avarage flight time per airline or number of flights per day

For this we can use groupby(), that splits the data into groups.

groupby() only defines the groups – you must follow it with an aggregation such as
.mean(), .sum(), .count(), or .agg(…) to compute results.

In [65]:
fligts.groupby("AIRLINE")['AIR_TIME'].mean().head(5)

AIRLINE
AA    219.481334
AS    141.018698
B6    309.795684
DL    207.072013
F9    159.940407
Name: AIR_TIME, dtype: float64

Instead of selecting one column first, we can compute the mean of several numeric
columns per group and the result will be a DataFrame:

In [68]:
fligts.groupby('AIRLINE')[['AIR_TIME', 'DISTANCE']].mean().head(5)

           AIR_TIME     DISTANCE
AIRLINE
AA       219.481334  1739.233068
AS       141.018698  1040.034006
B6       309.795684  2486.148856
DL       207.072013  1656.216475
F9       159.940407  1235.666426

Note, that returned object is Series with unique "AIRLINE" values being in the index
column.

--------

### .size()

We can also compute the number of rows in each group using .size() directly after
groupby() (or .count() on any column):

In [67]:
fligts.groupby('AIRLINE').size().head()

AIRLINE
AA    65483
AS    16144
B6     8216
DL    50343
F9     2770
dtype: int64

-------

### .agg()

Instead of one summary per column, .agg() lets us compute several stats at
once—per group.

In [71]:
fligts.groupby('AIRLINE').agg( {
    'AIR_TIME': ['mean','std'],
    'DISTANCE': ['min'],
    'DESTINATION_AIRPORT': ['size', 'first', 'nunique']
    }
).head(5)

           AIR_TIME            DISTANCE DESTINATION_AIRPORT
               mean        std      min                size first nunique
AIRLINE
AA       219.481334  92.889719    236.0               65483   PBI      31
AS       141.018698  51.806424    590.0               16144   SEA       7
B6       309.795684  28.457740    954.0                8216   JFK       5
DL       207.072013  88.908566    109.0               50343   MSP      31
F9       159.940407  61.412379    862.0                2770   LAX       5

In [74]:
fligts[ fligts['MONTH'].isin(range(6,9)) ].groupby('ORIGIN_AIRPORT').size().head(5)

ORIGIN_AIRPORT
ABQ     632
ANC     169
ASE     173
ATL    1723
AUS     710
dtype: int64

---------

# Sorting

Another common operation is sorting, that can be done using
**.sort_values(col_name)** function:

In [78]:
fligts.sort_values('DISTANCE', ascending= False).head(5)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
169907,2015,5,29,5,AA,265,LAX,LIH,906.0,337.0,2615.0,1212.0
138515,2015,5,2,6,UA,297,LAX,LIH,903.0,315.0,2615.0,1139.0
378210,2015,12,21,1,AA,286,LIH,LAX,2251.0,315.0,2615.0,646.0
189410,2015,6,14,7,HA,64,LIH,LAX,1209.0,301.0,2615.0,2029.0
378187,2015,12,21,1,DL,1735,LIH,LAX,2219.0,308.0,2615.0,552.0

-----

# Extending Tables

## Creating a new column

We can create new columns by performing operations on existing ones:

In [86]:
fligts['DIST_MILES'] = fligts['DISTANCE'] * 0.621371
fligts.head(5)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME,DIST_MILES
0,2015,1,1,4,AA,2336,LAX,PBI,2.0,263.0,2330.0,741.0,1447.794430
1,2015,1,1,4,AA,258,LAX,MIA,15.0,258.0,2342.0,756.0,1455.250882
2,2015,1,1,4,US,2013,LAX,CLT,44.0,228.0,NaN,753.0,NaN
3,2015,1,1,4,DL,1434,LAX,MSP,35.0,188.0,1535.0,605.0,953.804485
4,2015,1,1,4,AA,115,LAX,MIA,103.0,255.0,2342.0,839.0,1455.250882

We can also combine columns to compute new values. Here we compute speed by
dividing distance by air time:

In [87]:
fligts['SPEED_MPH'] = (
    fligts['DIST_MILES'] / fligts['AIR_TIME'] * 60
)

fligts.head(5)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME,DIST_MILES,SPEED_MPH
0,2015,1,1,4,AA,2336,LAX,PBI,2.0,263.0,2330.0,741.0,1447.794430,330.295307
1,2015,1,1,4,AA,258,LAX,MIA,15.0,258.0,2342.0,756.0,1455.250882,338.430438
2,2015,1,1,4,US,2013,LAX,CLT,44.0,228.0,NaN,753.0,NaN,NaN
3,2015,1,1,4,DL,1434,LAX,MSP,35.0,188.0,1535.0,605.0,953.804485,304.405687
4,2015,1,1,4,AA,115,LAX,MIA,103.0,255.0,2342.0,839.0,1455.250882,342.411972

------

## Drop a Column

To delete column, you can use **.drop()** function and provide column names as a list:


This function return a new DataFrame by default. Use **inplace=True** to modify the
DataFrame directly.

In [88]:
fligts.drop(columns = ['DIST_MILES', 'SPEED_MPH'], inplace= True)
fligts.head(5)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_TIME,AIR_TIME,DISTANCE,ARRIVAL_TIME
0,2015,1,1,4,AA,2336,LAX,PBI,2.0,263.0,2330.0,741.0
1,2015,1,1,4,AA,258,LAX,MIA,15.0,258.0,2342.0,756.0
2,2015,1,1,4,US,2013,LAX,CLT,44.0,228.0,NaN,753.0
3,2015,1,1,4,DL,1434,LAX,MSP,35.0,188.0,1535.0,605.0
4,2015,1,1,4,AA,115,LAX,MIA,103.0,255.0,2342.0,839.0

----

# Copy DataFrame

To create a copy of the table you can use **.copy()**:

In [89]:
fligts_new = fligts.copy()

-------